[package]
name = "vocreader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.2.4", features = ["web"] }
epub = "1.2.4"
yomi-dict = { git = "ssh://git@github.com/ShaddyDC/yomi-dict.git" }

[dependencies.web-sys]
version = "0.3"
# TODO CHeck Window necessary
features = ["console", "Selection", "Window"]
